version: "3.7"
services:
  postgresql:
    image: docker.io/postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tradedb
      POSTGRES_USER: tradedb
      POSTGRES_DB: tradedb
  dbadminer:
    image: docker.io/adminer
    ports:
      - "9090:8080"
    environment:
      ADMINER_DESIGN: 'nette'
      ADMINER_DEFAULT_SERVER: "postgresql"
