service: aws-lambda-java-webdriver-example

provider:
  name: aws
  runtime: java11
  profile: serverless-admin
  region: eu-central-1
  timeout: 10
  memorySize: 2048
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221

functions:
  invokeWebDriver:
    image: 547530709389.dkr.ecr.eu-central-1.amazonaws.com/lambda-java-chrome:20
