# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: daytrader-dev

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - msa-placement-rule.yaml
  - ch-app-sub.yaml