apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradr
  labels:
    app.kubernetes.io/part-of: Quarkus-DayTrader
    app.kubernetes.io/name: nodejs
spec:
  selector:
    matchLabels:
      app: tradr
  template:
    metadata:
      labels:
        app: tradr
    spec:
      containers:
        - name: tradr
          image: quay.io/kameshsampath/tradr
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
