version: '3'
services:
  order-application:
    build: order-application
    ports:
      - "8080:8080"
    links: 
      - user-management-application
  user-management-application:
    build: user-management-application