kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-ee-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-ee-kubernetes
  template:
    metadata:
      labels:
        app: java-ee-kubernetes
    spec:
      containers:
        - name: java-ee-kubernetes
          image: eu.gcr.io/java-ee-2-cloud/java-ee-kubernetes:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: java-ee-kubernetes
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: java-ee-kubernetes
