spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres  jpa:    hibernate:      ddl-auto: validate
    properties:      hibernate: 
        dialect: de.rieckpil.blog.ExtendedPostgreSQLDialect    show-sql: true